---
- name: Install essential packages on Ubuntu Server
  hosts: ubuntuserver-test # Can be any device
  become: yes  # Use 'become' for privilege escalation (sudo/root)

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install essential packages
      apt:
        name: 
          - htop
          - git
          - curl
          - neofetch
          - python3-full
          - samba
          - apache2
          - pip
          - net-tools
          - openssh-server
        state: present


    - name: Activate apache2
      service:
        name: apache2
        state: started
        enabled: yes
