- name: Truncate log file to 0
  hosts: ubuntu (Can be changed to any host running Nextcloud)
  become: yes
  tasks:
    - name: Truncate the log file using shell command
      shell: truncate -s 0 /var/www/nextcloud/data/nextcloud.log
      
